services:
  - type: web
    name: mitadt-mess-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py makemigrations --empty testapp && python manage.py makemigrations testapp && python manage.py migrate --run-syncdb && python manage.py migrate sessions && python manage.py migrate auth && python manage.py migrate contenttypes && python manage.py migrate admin && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@mitadt.edu.in', 'admin123') if not User.objects.filter(is_superuser=True).exists() else None\" && python manage.py create_feedback_periods"
    startCommand: "python manage.py collectstatic --noinput && gunicorn mitadt_mess.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    autoDeploy: true
