# Generated by Django 5.1 on 2025-11-14 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 14, 9, 33, 6, 424716, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='mess_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
