# Generated by Django 5.1 on 2025-11-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_complaint_created_at_alter_complaint_mess_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangeetrating',
            name='sangeet_menu',
        ),
        migrations.RemoveField(
            model_name='sangeetrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sofarating',
            name='sofa_menu',
        ),
        migrations.RemoveField(
            model_name='sofarating',
            name='user',
        ),
        migrations.DeleteModel(
            name='sangeet_menu',
        ),
        migrations.DeleteModel(
            name='SangeetRating',
        ),
        migrations.DeleteModel(
            name='sofa_menu',
        ),
        migrations.DeleteModel(
            name='SofaRating',
        ),
    ]
