# Generated by Django 5.1 on 2025-10-23 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rajmessdish_delete_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rajmessdish',
            options={'ordering': ['day', 'meal', 'dish_name']},
        ),
        migrations.AddField(
            model_name='rajmessdish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rajmessdish',
            name='dish_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rajmessdish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rajmess_dishes/'),
        ),
        migrations.AlterField(
            model_name='rajmessdish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
