# Generated by Django 5.1 on 2025-10-23 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_dish_added_at_alter_dish_day_alter_dish_meal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('user', 'week_start_date', 'day')},
            },
        ),
    ]
