# Generated by Django 5.1 on 2025-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_mealsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_breakfast', models.CharField(max_length=100)),
                ('monday_lunch', models.CharField(max_length=100)),
                ('monday_dinner', models.CharField(max_length=100)),
                ('tuesday_breakfast', models.CharField(max_length=100)),
                ('tuesday_lunch', models.CharField(max_length=100)),
                ('tuesday_dinner', models.CharField(max_length=100)),
                ('wednesday_breakfast', models.CharField(max_length=100)),
                ('wednesday_lunch', models.CharField(max_length=100)),
                ('wednesday_dinner', models.CharField(max_length=100)),
                ('thursday_breakfast', models.CharField(max_length=100)),
                ('thursday_lunch', models.CharField(max_length=100)),
                ('thursday_dinner', models.CharField(max_length=100)),
                ('friday_breakfast', models.CharField(max_length=100)),
                ('friday_lunch', models.CharField(max_length=100)),
                ('friday_dinner', models.CharField(max_length=100)),
                ('saturday_breakfast', models.CharField(max_length=100)),
                ('saturday_lunch', models.CharField(max_length=100)),
                ('saturday_dinner', models.CharField(max_length=100)),
                ('sunday_breakfast', models.CharField(max_length=100)),
                ('sunday_lunch', models.CharField(max_length=100)),
                ('sunday_dinner', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MealSuggestion',
        ),
    ]
