# Generated by Django 5.1 on 2025-10-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_weeklyfeedback_delete_mealsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyfeedback',
            name='monday_lunch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
