# Generated by Django 5.1 on 2025-10-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_weeklyfeedback_monday_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyfeedback',
            name='monday_lunch',
            field=models.CharField(max_length=100),
        ),
    ]
