# Generated by Django 5.1 on 2025-10-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_weeklyfeedback_monday_lunch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyFeedback',
            new_name='raj_WeeklyFeedback',
        ),
    ]
