# Generated by Django 5.1 on 2025-10-29 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_dishrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testapp.dish'),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together={('dish', 'user')},
        ),
    ]
