# Generated by Django 5.1 on 2025-10-29 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_dishrating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together={('user', 'dish')},
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
