# Generated by Django 5.1 on 2025-10-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_dishrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.dish'),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
