# Generated by Django 5.1 on 2025-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_mess_alter_dish_day_alter_dish_image_alter_dish_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='mess',
        ),
        migrations.AlterField(
            model_name='dish',
            name='day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dish_images/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='meal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
