# Generated by Django 5.1 on 2025-11-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_remove_dish_mess_alter_dish_day_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='mess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.mess'),
            preserve_default=False,
        ),
    ]
