# Generated by Django 5.1 on 2025-11-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_messselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='messselection',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
