# Generated by Django 5.1 on 2025-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_messselection_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('DOME VISITOR', 'DOME VISITOR'), ('Dean/Director/Faculty/Staff', 'Dean/Director/Faculty/Staff'), ('Other', 'Other')], max_length=50)),
                ('mess_name', models.CharField(choices=[('Raj Mess', 'Raj Mess'), ('MANET Mess', 'MANET Mess'), ('Sangeet Mess', 'Sangeet Mess'), ('Design Mess', 'Design Mess'), ('Sofa Mess', 'Sofa Mess')], max_length=50)),
                ('alumni', models.CharField(max_length=5)),
                ('dome_visitor', models.CharField(max_length=5)),
                ('contact', models.CharField(max_length=15)),
                ('visit_date', models.DateField()),
                ('food_rating', models.IntegerField()),
                ('food_comment', models.TextField()),
                ('service_rating', models.IntegerField()),
                ('service_comment', models.TextField()),
                ('cleanliness_rating', models.IntegerField()),
                ('cleanliness_comment', models.TextField()),
                ('overall_rating', models.IntegerField()),
                ('suggestion', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
