# Generated by Django 5.1 on 2025-11-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_designrating_sangeetrating_sofarating'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrating',
            name='mess_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='designrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
