# Generated by Django 5.1 on 2025-11-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_designrating_mess_id_alter_designrating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designrating',
            unique_together={('user', 'design_menu')},
        ),
        migrations.AlterField(
            model_name='designrating',
            name='design_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testapp.design_menu'),
        ),
        migrations.AlterField(
            model_name='designrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='mess_id',
        ),
    ]
