# Generated by Django 5.1 on 2025-11-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0030_alter_designrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrating',
            name='design_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.design_menu'),
        ),
        migrations.AlterField(
            model_name='designrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
