# Generated by Django 5.1 on 2025-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_alter_designrating_design_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(choices=[('MANET Mess', 'MANET Mess'), ('Design Mess', 'Design Mess'), ('Sofa Mess', 'Sofa Mess'), ('Raj Mess', 'Raj Mess'), ('Sangeet Mess', 'Sangeet Mess')], max_length=100)),
                ('monday_breakfast', models.CharField(max_length=100)),
                ('monday_lunch', models.CharField(max_length=100)),
                ('monday_dinner', models.CharField(max_length=100)),
                ('tuesday_breakfast', models.CharField(max_length=100)),
                ('tuesday_lunch', models.CharField(max_length=100)),
                ('tuesday_dinner', models.CharField(max_length=100)),
                ('wednesday_breakfast', models.CharField(max_length=100)),
                ('wednesday_lunch', models.CharField(max_length=100)),
                ('wednesday_dinner', models.CharField(max_length=100)),
                ('thursday_breakfast', models.CharField(max_length=100)),
                ('thursday_lunch', models.CharField(max_length=100)),
                ('thursday_dinner', models.CharField(max_length=100)),
                ('friday_breakfast', models.CharField(max_length=100)),
                ('friday_lunch', models.CharField(max_length=100)),
                ('friday_dinner', models.CharField(max_length=100)),
                ('saturday_breakfast', models.CharField(max_length=100)),
                ('saturday_lunch', models.CharField(max_length=100)),
                ('saturday_dinner', models.CharField(max_length=100)),
                ('sunday_breakfast', models.CharField(max_length=100)),
                ('sunday_lunch', models.CharField(max_length=100)),
                ('sunday_dinner', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='raj_WeeklyFeedback',
        ),
    ]
