# Generated by Django 5.1 on 2025-11-10 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_alter_notice_options_remove_notice_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='body',
            field=models.TextField(default='No content available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/attachments/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
