# Generated by Django 5.1 on 2025-11-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_alter_notice_attachment_alter_notice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='mess',
            new_name='mess_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved',
        ),
    ]
