# Generated by Django 5.1 on 2025-11-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='mess_name',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
