# Generated by Django 5.1 on 2025-11-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_complaint_created_at_complaint_mess_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testapp/images/design'),
        ),
        migrations.AlterField(
            model_name='designrating',
            name='design_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testapp.design_menu'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='meal',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='manet_menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testapp/images'),
        ),
        migrations.AlterField(
            model_name='sangeet_menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testapp/images/sangeet'),
        ),
        migrations.AlterField(
            model_name='sangeetrating',
            name='sangeet_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testapp.sangeet_menu'),
        ),
        migrations.AlterField(
            model_name='sofa_menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testapp/images/sofa'),
        ),
        migrations.AlterField(
            model_name='sofarating',
            name='sofa_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testapp.sofa_menu'),
        ),
    ]
