# Generated by Django 5.1 on 2025-11-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0038_alter_complaint_options_remove_complaint_created_at_and_more'),
        ('testapp', '0040_alter_design_menu_image_and_more'),
    ]

    operations = [
    ]
