# Generated by Django 5.1 on 2025-11-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_merge_20251114_1258'),
    ]

    operations = [
    ]
