# Generated by Django 6.0.3 on 2026-03-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_sangeetrating_sangeet_menu_and_more'),
        ('testapp', '0042_add_mess_name_to_complaint'),
    ]

    operations = [
    ]
