# Generated by Django 6.0.3 on 2026-03-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_merge_20260314_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Week 1 - March 2026'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_deadline', models.DateField(help_text='Last date to submit feedback')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='messfeedback',
            name='feedback_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messfeedback',
            name='feedback_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='messfeedback',
            unique_together={('email', 'feedback_period_start', 'feedback_period_end')},
        ),
    ]
