# Generated by Django 6.0.3 on 2026-03-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_feedbackperiod_messfeedback_feedback_period_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Feedback Period', 'verbose_name_plural': 'Feedback Periods'},
        ),
    ]
