# Generated by Django 6.0.3 on 2026-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_alter_feedbackperiod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Week 1 - March 2026'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_deadline', models.DateField(help_text='Last date to submit suggestions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suggestion Period',
                'verbose_name_plural': 'Suggestion Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='weekly_suggestion',
            name='suggestion_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weekly_suggestion',
            name='suggestion_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='weekly_suggestion',
            unique_together={('email', 'suggestion_period_start', 'suggestion_period_end')},
        ),
    ]
