# Generated by Django 6.0.3 on 2026-03-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_add_suggestion_period_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weekly_suggestion',
            unique_together={('email', 'mess_name', 'suggestion_period_start', 'suggestion_period_end')},
        ),
    ]
